language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'angular-preloaded' ]; then cd .. && eval "mv $currentfolder angular-preloaded" && cd angular-preloaded; fi
